name: Goreleaser

on:
  push:
    tags:
      - '*'

env:
  DOCKER_CLI_VERSION: "19.03.1"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.15.x'
      -
        name: Docker login
        run: make ci-docker-login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker logout
        run: make ci-docker-logout
      -
        name: Smoke test published image
        run: make ci-test-production-image
  
  npmjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: "https://registry.npmjs.org"
      - run: npm publish --ignore-scripts --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}